---
    name: Build Driver Toolkit images
    
    on:
      schedule:
        - cron: "0 0 * * *"
      workflow_dispatch:
    
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    
    jobs:
      build-matrix:
        runs-on: ubuntu-latest
        outputs:
          matrix: ${{ steps.gen-matrix.outputs.matrix }}
        steps:
          - name: Checkout current repository to get the matrix file
            uses: actions/checkout@v4
    
          - name: Generate the build matrix
            id: gen-matrix
            run: |
              ${GITHUB_WORKSPACE}/build-matrix.sh
              cat ${GITHUB_WORKSPACE}/build-matrix.json
              echo "matrix=$(cat ${GITHUB_WORKSPACE}/build-matrix.json)" >> $GITHUB_OUTPUT
    
      build-image:
        needs: build-matrix
        runs-on: ubuntu-latest
        if: ${{ needs.build-matrix.outputs.matrix != '{ "version": [  ] }' && needs.build-matrix.outputs.matrix != '' }}
        permissions:
          contents: read
          packages: write
        strategy:
          matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
          max-parallel: 1
          fail-fast: false
        steps:
          - name: Checkout current repository for the Dockerfiles
            uses: actions/checkout@v4
    
          - name: Lint Dockerfile
            uses: hadolint/hadolint-action@v3.1.0
            with:
              failure-threshold: error
    
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3
    
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
    
          - name: Login to the container registry
            uses: docker/login-action@v3
            with:
              registry: ${{ env.REGISTRY }}
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

          - name: "Build and push driver-toolkit:${{ matrix.version }}"
            uses: docker/build-push-action@v5
            with:
              context: .
              platforms: linux/amd64,linux/arm64
              push: true
              tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.version }}
              build-args: |
                "KERNEL_VERSION=${{ matrix.version }}"