---
name: Build Driver Toolkit images

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check-image:
    runs-on: ubuntu-latest
    outputs:
      kernel_version: ${{ steps.get-kernel-version.outputs.kernel_version }}
    steps:
      - name: Check if image already exists
        id: get-kernel-version
        continue-on-error: true
        run: |
          KERNEL_VERSION=$(skopeo inspect docker://quay.io/centos-bootc/centos-bootc:stream9 | jq -r '.Labels["ostree.linux"]')
          KERNEL_VERSION_NOARCH=$(echo ${KERNEL_VERSION} | sed "s/.$(arch)//")
          skopeo inspect docker://ghcr.io/fabiendupont/driver-toolkit:${KERNEL_VERSION_NOARCH} || echo "kernel_version=${KERNEL_VERSION_NOARCH}" >> $GITHUB_OUTPUT

  build-image:
    needs: check-image
    runs-on: ubuntu-latest
    env:
      KERNEL_VERSION: ${{ needs.check-image.outputs.kernel_version }}
    if: ${{ needs.check-image.outputs.kernel_version != '' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout current repository for the Dockerfiles
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          failure-threshold: error

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build and push driver-toolkit:${{ env.KERNEL_VERSION }}"
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.KERNEL_VERSION }}
          build-args: |
            "KERNEL_VERSION=${{ env.KERNEL_VERSION }}"
